apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: smokeping-prober
  name: smokeping-prober
  namespace: kube-prometheus-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smokeping-prober
  template:
    metadata:
      labels:
        app: smokeping-prober
    spec:
      containers:
      - image: quay.io/superq/smokeping-prober:latest
        name: smokeping-prober
        ports:
        - containerPort: 9374
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 512M
