---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tcp-persistent-prober
  namespace: kube-prometheus-stack

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tcp-persistent-prober
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tcp-persistent-prober
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tcp-persistent-prober
subjects:
- kind: ServiceAccount
  name: tcp-persistent-prober
  namespace: kube-prometheus-stack

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: tcp-persistent-prober
  name: tcp-persistent-prober
  namespace: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: tcp-persistent-prober
  template:
    metadata:
      labels:
        app: tcp-persistent-prober
    spec:
      serviceAccount: tcp-persistent-prober
      serviceAccountName: tcp-persistent-prober
      containers:
      - name: tcp-persistent-prober
        image: docker.io/cbaker090/tcp-persistent-prober:latest
        ports:
        - containerPort: 9060
          protocol: TCP
          name: prometheus
        - containerPort: 9061
          protocol: TCP
          name: echo
        resources:
          limits:
            cpu: 250m
            memory: 512M
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthy
            port: 9060
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 15
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: 9060
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 15
        env:
        - name: SERVICE_SELECTOR_NAMESPACE
          value: "kube-prometheus-stack"
        - name: SERVICE_SELECTOR
          value: "app=tcp-persistent-prober"
        - name: METRICS_PORT
          value: "9060"
        - name: ECHO_PORT
          value: "9061"
        - name: LOG_LEVEL
          value: "debug"
        - name: DISCOVERY_START_DELAY
          value: "30s"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
          

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tcp-persistent-prober
  name: tcp-persistent-prober
  namespace: kube-prometheus-stack
spec:
  type: NodePort
  ports:
  - name: echo
    port: 9061
    protocol: TCP
    targetPort: 9061
  selector:
    app: tcp-persistent-prober


---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    release: kube-prometheus-stack
  name: tcp-persistent-prober
  namespace: kube-prometheus-stack
spec:
  podMetricsEndpoints:
  - port: prometheus
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      action: replace
      targetLabel: node
  namespaceSelector:
    matchNames:
    - kube-prometheus-stack
  selector:
    matchLabels:
      app: tcp-persistent-prober
